TRANSACTION_STATUS_PENDING = "pending"
TRANSACTION_STATUS_SUCCESSFUL = "successful"
TRANSACTION_STATUS_FAILED = "failed"

TRANSACTION_STATUS = [
    (TRANSACTION_STATUS_PENDING, "Pending"),
    (TRANSACTION_STATUS_SUCCESSFUL, "Successful"),
    (TRANSACTION_STATUS_FAILED, "Failed"),
]
